[workspace]
resolver = "3"

members = [
    "crates/oopsie",
    "crates/oopsie-core",
    "crates/oopsie-macros",
]
exclude = ["crates/nostd-smoke"]

[workspace.package]
edition = "2024"
authors = ["Gaëtan Schwartz"]
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gaetschwartz/oopsie"
readme = "README.md"
keywords = ["error", "error-handling", "diagnostics", "backtrace", "spantrace"]
categories = ["rust-patterns", "development-tools::debugging"]

[workspace.dependencies]
oopsie-core = { path = "crates/oopsie-core", version = "0.1.0-rc.18", default-features = false }
oopsie-macros = { path = "crates/oopsie-macros", version = "0.1.0-rc.18" }
oopsie = { path = "crates/oopsie" }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

missing_errors_doc = "allow"
unreadable_literal = "allow"
wildcard_imports = "allow"
match_same_arms = "allow"
doc_markdown = "allow"
too_many_lines = "allow"
approx_constant = "allow"
unsafe_derive_deserialize = "allow"
struct_field_names = "allow"
similar_names = "allow"
inline_always = "allow"

# Additional nursery lints
significant_drop_tightening = "warn"
missing_const_for_fn = "warn"
needless_collect = "warn"
needless_pass_by_ref_mut = "warn"
or_fun_call = "warn"
read_zero_byte_vec = "warn"
redundant_clone = "warn"
redundant_pub_crate = "warn"
search_is_some = "warn"
significant_drop_in_scrutinee = "warn"
single_option_map = "warn"
type_repetition_in_bounds = "warn"
useless_let_if_seq = "warn"
iter_with_drain = "warn"
equatable_if_let = "warn"
clear_with_drain = "warn"
derive_partial_eq_without_eq = "warn"
trait_duplication_in_bounds = "warn"
fallible_impl_from = "warn"
branches_sharing_code = "warn"
collection_is_never_read = "warn"
empty_line_after_doc_comments = "warn"
empty_line_after_outer_attr = "warn"
iter_on_single_items = "warn"
iter_on_empty_collections = "warn"
set_contains_or_insert = "warn"
path_buf_push_overwrite = "warn"
string_lit_as_bytes = "warn"
debug_assert_with_mut_call = "warn"
tuple_array_conversions = "warn"
unused_peekable = "warn"
use_self = "warn"
cast_possible_truncation = "allow"

# Restrictions
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
assertions_on_result_states = "allow"
deref_by_slicing = "warn"
error_impl_error = "warn"
exit = "warn"
get_unwrap = "warn"
if_then_some_else_none = "warn"
map_err_ignore = "warn"
map_with_unused_argument_over_ranges = "warn"
non_zero_suggestions = "warn"
rc_buffer = "warn"
rest_pat_in_fully_bound_structs = "warn"
return_and_then = "warn"
str_to_string = "warn"
string_add = "warn"
string_lit_chars_any = "warn"
try_err = "warn"
unused_trait_names = "warn"
large_types_passed_by_value = "warn"
await_holding_lock = "warn"
await_holding_refcell_ref = "warn"
borrow_interior_mutable_const = "deny"
declare_interior_mutable_const = "deny"
unwrap_or_default = "warn"
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
mem_forget = "warn"
format_push_string = "warn"
clone_on_ref_ptr = "warn"
rc_mutex = "warn"
lossy_float_literal = "warn"
fn_to_numeric_cast_any = "warn"
empty_drop = "warn"
empty_structs_with_brackets = "warn"
verbose_file_reads = "warn"
unnecessary_self_imports = "warn"
as_underscore = "warn"
pub_without_shorthand = "warn"
nonstandard_macro_braces = "warn"
unnecessary_safety_comment = "warn"
print_stdout = "warn"
print_stderr = "warn"
redundant_type_annotations = "warn"
renamed_function_params = "warn"
ref_patterns = "warn"

[workspace.lints.rust]
unsafe_code = "deny"
unused_lifetimes = "warn"
redundant_lifetimes = "warn"
unit_bindings = "warn"
unnameable_types = "warn"
unused_macro_rules = "warn"
meta_variable_misuse = "warn"
unused_features = "allow" # Mutes some false positives in the presence of `cfg`-gated code, and the fact that some features are only used in doctests.

[workspace.lints.rustdoc]
broken_intra_doc_links = "warn"
private_intra_doc_links = "warn"
unescaped_backticks = "warn"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[profile.samply]
inherits = "release"
debug = true
