[package]
name = "oopsie"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[features]
default = ["daisy"]
unstable = ["oopsie-core/unstable", "oopsie-macros/unstable", "oopsie-daisy?/unstable"]
daisy = ["dep:oopsie-daisy", "oopsie-macros/daisy"]

[dependencies]
oopsie-core = { workspace = true }
oopsie-macros = { workspace = true }
oopsie-daisy = { workspace = true, optional = true }

[lints]
workspace = true

[dev-dependencies]
insta = { version = "1.46.3", features = ["filters", "json", "redactions"] }
strip-ansi-escapes = "0.2.1"
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
trybuild = "1.0.116"
