use core::error;

/// Builds a target error from a context selector and a source error of type `E`.
///
/// Implemented automatically by the context selector structs generated by
/// `#[derive(Oopsie)]`. You rarely implement this manually, and most code never
/// names it directly — [`ResultExt::context`] and [`OptionExt::context`] drive
/// it. Reach for it only when building an error outside a `Result`/`Option`,
/// e.g. `selector.build_error(source)`.
pub trait Contextual<E> {
    /// The destination error type being built by this context selector.
    type Destination;

    /// Build the target error from this context selector and the source error.
    #[track_caller]
    fn build_error(self, source: E) -> Self::Destination;
}

/// A type that can auto-capture diagnostic data at the point of error construction.
///
/// Implemented by [`Backtrace`](crate::Backtrace) and [`SpanTrace`](crate::SpanTrace) so they
/// can be filled automatically. Mark a field with `#[oopsie(capture)]` to have it populated
/// via this trait when the error is constructed — the field will not appear in the context
/// selector and will not need to be supplied by the caller.
pub trait Capturable {
    /// Capture diagnostic data at the current call site.
    #[track_caller]
    fn capture() -> Self;
}

impl<T: Capturable> Capturable for Box<T> {
    #[track_caller]
    #[inline]
    fn capture() -> Self {
        Self::new(T::capture())
    }
}

impl<A: Capturable, B: Capturable> Capturable for (A, B) {
    #[track_caller]
    #[inline]
    fn capture() -> Self {
        (A::capture(), B::capture())
    }
}

/// Extension of [`Capturable`] that tries to reuse traces from a source error.
///
/// When an error with a source implements [`Diagnostic`](crate::Diagnostic), this trait
/// extracts the existing backtrace/spantrace rather than capturing a new one, which
/// preserves the original call site. Falls back to [`Capturable::capture`] otherwise.
#[doc(hidden)]
pub trait CaptureExt: Capturable {
    #[track_caller]
    fn capture_or_extract(source: &dyn crate::Diagnostic) -> Self
    where
        Self: Sized;
}

impl<T: CaptureExt> CaptureExt for Box<T> {
    #[track_caller]
    fn capture_or_extract(source: &dyn crate::Diagnostic) -> Self {
        Self::new(T::capture_or_extract(source))
    }
}

impl<A: CaptureExt, B: CaptureExt> CaptureExt for (A, B) {
    #[track_caller]
    fn capture_or_extract(source: &dyn crate::Diagnostic) -> Self {
        (A::capture_or_extract(source), B::capture_or_extract(source))
    }
}

/// Unit source type used by [`OptionExt`] context selectors and leaf errors.
///
/// Leaf errors (those with no chained source) take this as the `source`
/// argument of [`Contextual::build_error`]. You will see it in type signatures
/// when working with [`OptionExt::context`] or when implementing [`Contextual`]
/// manually.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct NoSource;

/// Normalize any source-error value to a `&(dyn Error + 'static)`.
///
/// `#[derive(Oopsie)]` calls `source.as_error_source()` when emitting
/// `Error::source` for a variant with a `source` field. Method resolution
/// plus autoderef pick the right impl regardless of whether the field is
/// `MyError`, `Box<MyError>`, or `Box<dyn Error + Send + Sync + 'static>`.
///
/// The explicit `dyn Error + …` impls exist because the blanket
/// `impl<T: Error + 'static> AsErrorSource for T` can't reach the autoderef
/// target of `Box<dyn Error + Send + Sync>` — that target is `?Sized` and the
/// blanket implicitly requires `Sized`. Without those impls the boxed-dyn
/// case fails to typecheck because stdlib's `impl<E: Error> Error for Box<E>`
/// also requires `E: Sized`.
pub trait AsErrorSource {
    /// Borrow this value as a `&(dyn Error + 'static)`.
    fn as_error_source(&self) -> &(dyn error::Error + 'static);
}

impl<T: error::Error + 'static> AsErrorSource for T {
    #[inline]
    fn as_error_source(&self) -> &(dyn error::Error + 'static) {
        self
    }
}

impl AsErrorSource for dyn error::Error + 'static {
    #[inline]
    fn as_error_source(&self) -> &(dyn error::Error + 'static) {
        self
    }
}

impl AsErrorSource for dyn error::Error + Send + 'static {
    #[inline]
    fn as_error_source(&self) -> &(dyn error::Error + 'static) {
        self
    }
}

impl AsErrorSource for dyn error::Error + Send + Sync + 'static {
    #[inline]
    fn as_error_source(&self) -> &(dyn error::Error + 'static) {
        self
    }
}

/// Extension trait on [`Result`] for ergonomic error context wrapping.
///
/// Import via `use oopsie::prelude::*` or `use oopsie::ResultExt`.
///
/// # Example
///
/// ```
/// use oopsie::{Oopsie, ResultExt as _};
///
/// #[derive(Debug, Oopsie)]
/// #[oopsie(module(false))]
/// enum IoError {
///     #[oopsie("IO failed: {source}")]
///     Failed { source: std::io::Error },
/// }
///
/// # fn main() {
/// let result: Result<(), std::io::Error> = Err(std::io::Error::other("disk full"));
/// let err = result.context(Failed).unwrap_err();
/// assert_eq!(err.to_string(), "IO failed: disk full");
/// # }
/// ```
pub trait ResultExt<T, E> {
    /// Wrap the error with an eagerly-evaluated context selector.
    fn context<C>(self, context: C) -> Result<T, C::Destination>
    where
        C: Contextual<E>;

    /// Wrap the error with a lazily-evaluated context selector.
    fn with_context<F, C>(self, context: F) -> Result<T, C::Destination>
    where
        F: FnOnce(&E) -> C,
        C: Contextual<E>;
}

impl<T, E> ResultExt<T, E> for Result<T, E> {
    #[inline]
    #[track_caller]
    fn context<C>(self, context: C) -> Result<T, C::Destination>
    where
        C: Contextual<E>,
    {
        self.map_err(|error| context.build_error(error))
    }

    #[inline]
    #[track_caller]
    fn with_context<F, C>(self, context: F) -> Result<T, C::Destination>
    where
        F: FnOnce(&E) -> C,
        C: Contextual<E>,
    {
        self.map_err(|error| context(&error).build_error(error))
    }
}

/// Extension trait on [`Option`] for converting `None` into a typed error.
///
/// Import via `use oopsie::prelude::*` or `use oopsie::OptionExt`.
///
/// # Example
///
/// ```
/// use oopsie::{Oopsie, OptionExt as _};
///
/// #[derive(Debug, Oopsie)]
/// #[oopsie(module(false))]
/// enum LookupError {
///     #[oopsie("Key not found: {key}")]
///     Missing { key: String },
/// }
///
/// # fn main() {
/// let opt: Option<i32> = None;
/// let err = opt.context(Missing { key: "host" }).unwrap_err();
/// assert_eq!(err.to_string(), "Key not found: host");
/// # }
/// ```
pub trait OptionExt<T> {
    /// Convert `None` into an error with an eagerly-evaluated context selector.
    fn context<C>(self, context: C) -> Result<T, C::Destination>
    where
        C: Contextual<NoSource>;

    /// Convert `None` into an error with a lazily-evaluated context selector.
    fn with_context<F, C>(self, context: F) -> Result<T, C::Destination>
    where
        F: FnOnce() -> C,
        C: Contextual<NoSource>;
}

impl<T> OptionExt<T> for Option<T> {
    #[inline]
    #[track_caller]
    fn context<C>(self, context: C) -> Result<T, C::Destination>
    where
        C: Contextual<NoSource>,
    {
        self.ok_or_else(|| context.build_error(NoSource))
    }

    #[inline]
    #[track_caller]
    fn with_context<F, C>(self, context: F) -> Result<T, C::Destination>
    where
        F: FnOnce() -> C,
        C: Contextual<NoSource>,
    {
        self.ok_or_else(|| context().build_error(NoSource))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::error::Error as StdError;
    use std::fmt;

    // Test error types for trait implementations
    #[derive(Debug)]
    struct SimpleError {
        message: String,
    }

    impl fmt::Display for SimpleError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(f, "{}", self.message)
        }
    }

    impl std::error::Error for SimpleError {}

    #[derive(Debug)]
    struct SourceError {
        message: String,
    }

    impl fmt::Display for SourceError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(f, "{}", self.message)
        }
    }

    impl std::error::Error for SourceError {}

    #[derive(Debug)]
    struct ChainError {
        message: String,
        source: Box<SourceError>,
    }

    impl fmt::Display for ChainError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(f, "{}", self.message)
        }
    }

    impl std::error::Error for ChainError {
        fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
            Some(&*self.source)
        }
    }

    // Test Contextual selector implementations
    struct SimpleSelector;

    impl Contextual<NoSource> for SimpleSelector {
        type Destination = SimpleError;

        fn build_error(self, _source: NoSource) -> SimpleError {
            SimpleError {
                message: "simple error".to_owned(),
            }
        }
    }

    struct ChainSelector;

    impl Contextual<SourceError> for ChainSelector {
        type Destination = ChainError;

        fn build_error(self, source: SourceError) -> ChainError {
            ChainError {
                message: "chain error".to_owned(),
                source: Box::new(source),
            }
        }
    }

    #[test]
    fn test_result_ext_context_ok() {
        let result: Result<i32, SourceError> = Ok(42);
        let chained: Result<i32, ChainError> = result.context(ChainSelector);
        assert!(chained.is_ok());
        assert_eq!(chained.unwrap(), 42);
    }

    #[test]
    fn test_result_ext_context_err() {
        let result: Result<i32, SourceError> = Err(SourceError {
            message: "source failed".to_owned(),
        });
        let chained: Result<i32, ChainError> = result.context(ChainSelector);
        assert!(chained.is_err());
        let err = chained.unwrap_err();
        assert_eq!(err.message, "chain error");
        assert_eq!(StdError::source(&err).unwrap().to_string(), "source failed");
    }

    #[test]
    fn test_result_ext_with_context_ok() {
        let result: Result<i32, SourceError> = Ok(42);
        let chained: Result<i32, ChainError> = result.with_context(|_| ChainSelector);
        assert!(chained.is_ok());
        assert_eq!(chained.unwrap(), 42);
    }

    #[test]
    fn test_result_ext_with_context_err_closure_called() {
        let mut closure_called = false;
        let result: Result<i32, SourceError> = Err(SourceError {
            message: "source failed".to_owned(),
        });
        let chained: Result<i32, ChainError> = result.with_context(|source| {
            closure_called = true;
            // Verify we can access the source in the closure
            assert_eq!(source.message, "source failed");
            ChainSelector
        });
        assert!(closure_called);
        chained.unwrap_err();
    }

    #[test]
    fn test_option_ext_context_some() {
        let option: Option<i32> = Some(42);
        let result: Result<i32, SimpleError> = option.context(SimpleSelector);
        assert!(result.is_ok());
        assert_eq!(result.unwrap(), 42);
    }

    #[test]
    fn test_option_ext_context_none() {
        let option: Option<i32> = None;
        let result: Result<i32, SimpleError> = option.context(SimpleSelector);
        assert!(result.is_err());
        assert_eq!(result.unwrap_err().message, "simple error");
    }

    #[test]
    fn test_option_ext_with_context_some() {
        let option: Option<i32> = Some(42);
        let result: Result<i32, SimpleError> = option.with_context(|| SimpleSelector);
        assert!(result.is_ok());
        assert_eq!(result.unwrap(), 42);
    }

    #[test]
    fn test_option_ext_with_context_none_closure_called() {
        let mut closure_called = false;
        let option: Option<i32> = None;
        let result: Result<i32, SimpleError> = option.with_context(|| {
            closure_called = true;
            SimpleSelector
        });
        assert!(closure_called);
        result.unwrap_err();
    }

    const _: () = {
        // Verify that Box<T> implements Capturable when T: Capturable
        const fn is_capturable<T: Capturable>() {}
        is_capturable::<Box<crate::Backtrace>>();
    };

    #[test]
    fn tuple_capture_produces_both_elements() {
        use crate::{Backtrace, SpanTrace};
        // Tuple capture yields both traces; neither call panics.
        let (bt, st): (Backtrace, SpanTrace) = <(Backtrace, SpanTrace) as Capturable>::capture();
        let _ = bt.frames();
        let _ = st.status();
    }

    const _: () = {
        const fn is_capturable<T: Capturable>() {}
        // The headline default layout must be Capturable for free via Box<T>.
        is_capturable::<Box<(crate::Backtrace, crate::SpanTrace)>>();
        is_capturable::<(crate::Backtrace, crate::SpanTrace)>();
    };

    #[test]
    fn tuple_capture_ext_extracts_both_from_source() {
        use crate::{Backtrace, CaptureExt, Diagnostic, SpanTrace};
        use std::fmt;

        #[derive(Debug)]
        struct Src {
            backtrace: Backtrace,
            spantrace: SpanTrace,
        }
        impl fmt::Display for Src {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str("src")
            }
        }
        impl std::error::Error for Src {}
        impl Diagnostic for Src {
            fn oopsie_backtrace(&self) -> Option<&Backtrace> {
                Some(&self.backtrace)
            }
            fn oopsie_spantrace(&self) -> Option<&SpanTrace> {
                Some(&self.spantrace)
            }
        }

        let src = Src {
            backtrace: Backtrace::capture(),
            spantrace: SpanTrace::capture(),
        };
        let extracted = <(Backtrace, SpanTrace) as CaptureExt>::capture_or_extract(&src);
        // The extracted backtrace must reuse the source's frame count, proving
        // extraction (not a fresh capture).
        assert_eq!(extracted.0.frames().len(), src.backtrace.frames().len());
    }

    const _: () = {
        const fn is_capture_ext<T: CaptureExt>() {}
        is_capture_ext::<Box<(crate::Backtrace, crate::SpanTrace)>>();
        is_capture_ext::<(crate::Backtrace, crate::SpanTrace)>();
    };
}
