//! `Welp` — a string-shaped escape hatch for prototypes, one-off errors,
//! and quick string contexts.
//!
//! The typed-selector flow generated by `#[oopsie]` is the project's primary
//! error-handling story. `Welp` covers the cases where a structured variant
//! would be overkill: prototyping, exactly-once failure modes, and adding a
//! plain-string context to a foreign error.
//!
//! ```
//! use oopsie_core::{Welp, WelpResultExt as _};
//!
//! fn read_config(path: &str) -> Result<String, Welp> {
//!     std::fs::read_to_string(path).welp_context("could not read config")
//! }
//! ```
//!
//! # Construction
//!
//! - [`Welp::new`] — fresh string error, captures backtrace and span-trace.
//! - [`Welp::wrap`] — wrap an existing error with a string message.
//!
//! # Adding context to a `Result` / `Option`
//!
//! Bring [`WelpResultExt`] / [`WelpOptionExt`] into scope (or import from
//! `oopsie::prelude`) and use [`welp_context`](WelpResultExt::welp_context) /
//! [`with_welp_context`](WelpResultExt::with_welp_context).
//!
//! # Layout
//!
//! `Welp` is a small enum — `Sourced` carries `Box<str>` + `Box<dyn Error>`,
//! `Traced` carries `Box<str>` + `Box<(Backtrace, SpanTrace)>`. The two
//! variants are mutually exclusive: a `Sourced` `Welp` captures no traces of
//! its own; a `Traced` `Welp` captures fresh traces at construction.
//!
//! A `Sourced` `Welp` still surfaces its source's traces when the
//! `unstable-error-generic-member-access` feature is enabled: its [`Diagnostic`]
//! accessors and `Error::provide` forward to the boxed source via the Provider
//! API, so an oopsie-aware source's backtrace/span-trace flows through. Without
//! that feature there is no portable way to reach into the source, so the
//! accessors return `None`.

use std::error::Error as StdError;
use std::fmt;

use crate::{Backtrace, Capturable as _, Diagnostic, SpanTrace};

/// A boxed `std::error::Error` that's `Send + Sync + 'static`.
type BoxError = Box<dyn StdError + Send + Sync + 'static>;

/// A string-shaped error type for prototypes, one-off errors, and quick
/// string contexts.
///
/// See the [module documentation](self) for a full overview.
#[must_use = "this `Welp` error should be returned or propagated, not discarded"]
pub struct Welp(WelpRepr);

enum WelpRepr {
    Sourced {
        message: Box<str>,
        source: BoxError,
    },
    Traced {
        message: Box<str>,
        traces: Box<(Backtrace, SpanTrace)>,
    },
}

impl Welp {
    /// Build a fresh `Welp` from a string message. Captures backtrace and
    /// span-trace at the call site.
    ///
    /// ```
    /// use oopsie_core::Welp;
    ///
    /// let err = Welp::new(format!("port {} out of range", 70_000));
    /// assert_eq!(err.to_string(), "port 70000 out of range");
    /// ```
    #[track_caller]
    pub fn new(message: impl Into<String>) -> Self {
        Self(WelpRepr::Traced {
            message: message.into().into_boxed_str(),
            traces: Box::new((Backtrace::capture(), SpanTrace::capture())),
        })
    }

    /// Wrap an existing error with a string message. `Welp::wrap` captures no
    /// traces of its own. With the `unstable-error-generic-member-access`
    /// feature it forwards traces the source provides through its [`Diagnostic`]
    /// accessors; otherwise those accessors return `None`.
    ///
    /// ```
    /// use oopsie_core::Welp;
    ///
    /// let io_err = std::io::Error::other("disk full");
    /// let err = Welp::wrap(io_err, "could not write");
    /// assert_eq!(err.to_string(), "could not write");
    /// assert!(std::error::Error::source(&err).is_some());
    /// ```
    #[track_caller]
    pub fn wrap<E>(source: E, message: impl Into<String>) -> Self
    where
        E: StdError + Send + Sync + 'static,
    {
        Self(WelpRepr::Sourced {
            message: message.into().into_boxed_str(),
            source: Box::new(source),
        })
    }

    /// Wrap an already-boxed trait-object error with a string message.
    ///
    /// Use this when the source comes from an API returning
    /// `Box<dyn Error + Send + Sync + 'static>` — that type is `?Sized` and
    /// can't satisfy [`wrap`](Self::wrap)'s `Sized` bound, but it's exactly
    /// the shape `Welp` stores internally, so no rewrapping is needed.
    ///
    /// ```
    /// use oopsie_core::Welp;
    ///
    /// let boxed: Box<dyn std::error::Error + Send + Sync + 'static> =
    ///     Box::new(std::io::Error::other("disk full"));
    /// let err = Welp::wrap_boxed(boxed, "could not write");
    /// assert_eq!(err.to_string(), "could not write");
    /// assert!(std::error::Error::source(&err).is_some());
    /// ```
    #[track_caller]
    pub fn wrap_boxed(source: BoxError, message: impl Into<String>) -> Self {
        Self(WelpRepr::Sourced {
            message: message.into().into_boxed_str(),
            source,
        })
    }

    /// The message attached to this error.
    #[must_use]
    #[inline]
    pub fn message(&self) -> &str {
        match &self.0 {
            WelpRepr::Sourced { message, .. } | WelpRepr::Traced { message, .. } => message,
        }
    }
}

impl fmt::Debug for Welp {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut dbg = f.debug_struct("Welp");
        dbg.field("message", &self.message());
        match &self.0 {
            WelpRepr::Sourced { source, .. } => {
                dbg.field("source", source);
            }
            WelpRepr::Traced { .. } => {}
        }
        dbg.finish()
    }
}

impl fmt::Display for Welp {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.message())
    }
}

impl StdError for Welp {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        match &self.0 {
            WelpRepr::Sourced { source, .. } => Some(&**source),
            WelpRepr::Traced { .. } => None,
        }
    }

    #[cfg(feature = "unstable-error-generic-member-access")]
    fn provide<'a>(&'a self, request: &mut core::error::Request<'a>) {
        match &self.0 {
            WelpRepr::Sourced { source, .. } => source.provide(request),
            WelpRepr::Traced { traces, .. } => {
                request
                    .provide_ref::<Backtrace>(&traces.0)
                    .provide_ref::<SpanTrace>(&traces.1);
            }
        }
    }
}

impl Diagnostic for Welp {
    fn oopsie_backtrace(&self) -> Option<&Backtrace> {
        match &self.0 {
            WelpRepr::Sourced { source, .. } => source_request_ref::<Backtrace>(source),
            WelpRepr::Traced { traces, .. } => Some(&traces.0),
        }
    }

    fn oopsie_spantrace(&self) -> Option<&SpanTrace> {
        match &self.0 {
            WelpRepr::Sourced { source, .. } => source_request_ref::<SpanTrace>(source),
            WelpRepr::Traced { traces, .. } => Some(&traces.1),
        }
    }
}

/// Pull a `T` reference out of a boxed source error via the Provider API. A
/// `Sourced` `Welp` carries no traces of its own, so the only way to surface a
/// source's backtrace/span-trace is to query what the source itself provides.
/// Without the unstable Provider API there is no portable way to do this, so
/// the trace is genuinely unavailable and we return `None`.
fn source_request_ref<T: 'static>(source: &BoxError) -> Option<&T> {
    crate::__private::source_trace::<T>(&**source)
}

/// Extension trait on [`Result`] for attaching a string message that produces
/// a [`Welp`].
///
/// Bring this into scope via `use oopsie::prelude::*` (or `use
/// oopsie_core::WelpResultExt`).
///
/// ```
/// use oopsie_core::{Welp, WelpResultExt as _};
///
/// fn read(path: &str) -> Result<String, Welp> {
///     std::fs::read_to_string(path).welp_context("could not read")
/// }
/// ```
pub trait WelpResultExt<T, E>: Sized {
    /// Wrap the error in a [`Welp`] with the given message.
    ///
    /// Note: the `message` argument is evaluated at the call site per Rust's
    /// eager-argument rules — `welp_context(format!(...))` allocates the
    /// formatted `String` even on the `Ok` branch. Use [`with_welp_context`]
    /// when the message is built from a non-trivial expression that should
    /// only run on `Err`.
    ///
    /// [`with_welp_context`]: Self::with_welp_context
    fn welp_context(self, message: impl Into<String>) -> Result<T, Welp>;

    /// Wrap the error in a [`Welp`] with a lazily-built message. The closure
    /// runs only on the `Err` branch and receives a shared reference to the
    /// source error.
    fn with_welp_context<S, F>(self, f: F) -> Result<T, Welp>
    where
        S: Into<String>,
        F: FnOnce(&E) -> S;
}

impl<T, E> WelpResultExt<T, E> for Result<T, E>
where
    E: StdError + Send + Sync + 'static,
{
    #[inline]
    #[track_caller]
    fn welp_context(self, message: impl Into<String>) -> Result<T, Welp> {
        self.map_err(|e| Welp::wrap(e, message))
    }

    #[inline]
    #[track_caller]
    fn with_welp_context<S, F>(self, f: F) -> Result<T, Welp>
    where
        S: Into<String>,
        F: FnOnce(&E) -> S,
    {
        self.map_err(|e| {
            let msg = f(&e);
            Welp::wrap(e, msg)
        })
    }
}

/// Extension trait on [`Option`] for converting `None` into a [`Welp`].
///
/// Bring this into scope via `use oopsie::prelude::*` (or `use
/// oopsie_core::WelpOptionExt`).
///
/// ```
/// use oopsie_core::{Welp, WelpOptionExt as _};
///
/// fn first_word(s: &str) -> Result<&str, Welp> {
///     s.split_whitespace().next().welp_context("string is empty")
/// }
/// ```
pub trait WelpOptionExt<T>: Sized {
    /// Convert `None` into a [`Welp`] with the given message.
    ///
    /// Note: the `message` argument is evaluated at the call site per Rust's
    /// eager-argument rules — `welp_context(format!(...))` allocates the
    /// formatted `String` even on the `Some` branch. Use [`with_welp_context`]
    /// when the message is built from a non-trivial expression that should
    /// only run on `None`.
    ///
    /// [`with_welp_context`]: Self::with_welp_context
    fn welp_context(self, message: impl Into<String>) -> Result<T, Welp>;

    /// Convert `None` into a [`Welp`] with a lazily-built message. The
    /// closure runs only on the `None` branch.
    fn with_welp_context<S, F>(self, f: F) -> Result<T, Welp>
    where
        S: Into<String>,
        F: FnOnce() -> S;
}

impl<T> WelpOptionExt<T> for Option<T> {
    #[inline]
    #[track_caller]
    fn welp_context(self, message: impl Into<String>) -> Result<T, Welp> {
        self.ok_or_else(|| Welp::new(message))
    }

    #[inline]
    #[track_caller]
    fn with_welp_context<S, F>(self, f: F) -> Result<T, Welp>
    where
        S: Into<String>,
        F: FnOnce() -> S,
    {
        self.ok_or_else(|| Welp::new(f()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_captures_message() {
        let err = Welp::new("hello");
        assert_eq!(err.message(), "hello");
        assert_eq!(err.to_string(), "hello");
    }

    #[test]
    fn new_accepts_string_and_str() {
        let _: Welp = Welp::new("static");
        let _: Welp = Welp::new(String::from("owned"));
        let _: Welp = Welp::new(format!("formatted {}", 1));
    }

    #[test]
    fn new_captures_traces() {
        let err = Welp::new("oops");
        assert!(err.oopsie_backtrace().is_some());
        assert!(err.oopsie_spantrace().is_some());
    }

    #[test]
    fn new_has_no_source() {
        let err = Welp::new("oops");
        assert!(StdError::source(&err).is_none());
    }

    #[test]
    fn wrap_carries_source() {
        let inner = std::io::Error::other("disk full");
        let err = Welp::wrap(inner, "could not write");
        assert_eq!(err.to_string(), "could not write");
        let source = StdError::source(&err).expect("source missing");
        assert_eq!(source.to_string(), "disk full");
    }

    #[test]
    fn wrap_does_not_capture_traces() {
        let err = Welp::wrap(std::io::Error::other("x"), "msg");
        assert!(err.oopsie_backtrace().is_none());
        assert!(err.oopsie_spantrace().is_none());
    }

    #[test]
    fn wrap_boxed_carries_source() {
        let boxed: BoxError = Box::new(std::io::Error::other("disk full"));
        let err = Welp::wrap_boxed(boxed, "could not write");
        assert_eq!(err.to_string(), "could not write");
        assert_eq!(
            StdError::source(&err).expect("source missing").to_string(),
            "disk full"
        );
    }

    #[test]
    fn welp_context_on_ok_is_passthrough() {
        let r: Result<i32, std::io::Error> = Ok(42);
        let mapped: Result<i32, Welp> = r.welp_context("nope");
        assert_eq!(mapped.unwrap(), 42);
    }

    #[test]
    fn welp_context_on_err_produces_sourced_welp() {
        let r: Result<i32, std::io::Error> = Err(std::io::Error::other("io fail"));
        let err = r.welp_context("read failed").unwrap_err();
        assert_eq!(err.to_string(), "read failed");
        assert_eq!(StdError::source(&err).unwrap().to_string(), "io fail");
    }

    #[test]
    fn with_welp_context_does_not_run_closure_on_ok() {
        let r: Result<i32, std::io::Error> = Ok(1);
        let mapped: Result<i32, Welp> = r.with_welp_context(|_| -> String {
            panic!("should not run");
        });
        mapped.unwrap();
    }

    #[test]
    fn with_welp_context_runs_closure_on_err() {
        let r: Result<i32, std::io::Error> = Err(std::io::Error::other("inner"));
        let err = r
            .with_welp_context(|e| format!("wrapped: {e}"))
            .unwrap_err();
        assert_eq!(err.to_string(), "wrapped: inner");
    }

    #[test]
    fn option_welp_context_on_some_is_passthrough() {
        let opt: Option<i32> = Some(7);
        assert_eq!(opt.welp_context("missing").unwrap(), 7);
    }

    #[test]
    fn option_welp_context_on_none_produces_traced_welp() {
        let opt: Option<i32> = None;
        let err = opt.welp_context("missing").unwrap_err();
        assert_eq!(err.to_string(), "missing");
        assert!(err.oopsie_backtrace().is_some());
        assert!(StdError::source(&err).is_none());
    }

    #[test]
    fn option_with_welp_context_does_not_run_closure_on_some() {
        let opt: Option<i32> = Some(1);
        let mapped: Result<i32, Welp> =
            opt.with_welp_context(|| -> String { panic!("should not run") });
        mapped.unwrap();
    }

    #[test]
    fn option_with_welp_context_runs_closure_on_none() {
        let opt: Option<i32> = None;
        let err = opt
            .with_welp_context(|| format!("missing key {}", "host"))
            .unwrap_err();
        assert_eq!(err.to_string(), "missing key host");
    }

    #[test]
    fn debug_includes_source_for_sourced() {
        let err = Welp::wrap(std::io::Error::other("inner"), "outer");
        let dbg = format!("{err:?}");
        assert!(dbg.contains("outer"));
        assert!(dbg.contains("inner"));
    }

    #[test]
    fn debug_omits_source_for_traced() {
        let err = Welp::new("solo");
        let dbg = format!("{err:?}");
        assert!(dbg.contains("solo"));
        assert!(!dbg.contains("source"));
    }

    #[cfg(feature = "unstable-error-generic-member-access")]
    #[test]
    fn traced_provides_traces_via_request_ref() {
        let err = Welp::new("solo");
        assert!(core::error::request_ref::<Backtrace>(&err).is_some());
        assert!(core::error::request_ref::<SpanTrace>(&err).is_some());
    }

    #[cfg(feature = "unstable-error-generic-member-access")]
    #[test]
    fn sourced_recovers_traces_from_diagnostic_source() {
        let outer = Welp::wrap(Welp::new("inner"), "outer");
        assert!(outer.oopsie_backtrace().is_some());
        assert!(outer.oopsie_spantrace().is_some());
    }

    #[cfg(feature = "unstable-error-generic-member-access")]
    #[test]
    fn sourced_forwards_source_provide() {
        let outer = Welp::wrap(Welp::new("inner"), "outer");
        assert!(core::error::request_ref::<Backtrace>(&outer).is_some());
        assert!(core::error::request_ref::<SpanTrace>(&outer).is_some());
    }

    #[cfg(feature = "unstable-error-generic-member-access")]
    #[test]
    fn sourced_recovers_nothing_from_foreign_source() {
        let outer = Welp::wrap(std::io::Error::other("x"), "outer");
        assert!(outer.oopsie_backtrace().is_none());
        assert!(outer.oopsie_spantrace().is_none());
    }

    // Compile-time guarantees about `Welp`'s shape.
    const _: () = {
        const fn assert_send<T: Send>() {}
        const fn assert_sync<T: Sync>() {}
        const fn assert_static<T: 'static>() {}
        assert_send::<Welp>();
        assert_sync::<Welp>();
        assert_static::<Welp>();
    };
}
