[package]
name = "erased-oopsie"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[features]
default = []
unstable = ["oopsie-core/unstable"]

[dependencies]
backtrace = "0.3.76"
oopsie-core = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.28", features = ["derive"] }
tracing = "0.1"

[dev-dependencies]
insta = { version = "1.46.3", features = ["filters", "json", "redactions"] }
oopsie = { workspace = true }
regex = "1.12.3"
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

[lints]
workspace = true
